version: "3.4"
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: ./etc/nginx
        target: /etc/nginx
      - type: bind
        source: ./www
        target: /usr/share/nginx/html
  certbot:
    image: certbot/certbot
    volumes:
      - type: bind
        source: ./etc/letsencrypt
        target: /etc/letsencrypt
      - type: bind
        source: ./www
        target: /usr/share/nginx/html
    command: ["certonly", "--agree-tos", "--webroot", "--register-unsafely-without-email", "-w", "/usr/share/nginx/html", "-d", "${DOMAIN}"]
